version: '3.5'

services:
  software-db-enterprise-com:
    image: ${DOCKER_REGISTRY}software-db.enterprise.com:${BRANCH}.${VERSION}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
    labels:
      kompose.service.expose: software-db.enterprise.com

networks:
  default:
    name: ns-software
